### ISSUE TITLE
Wrong workpath

### ISSUE THREAD

**Issue by piotrku91** [coders-school/lambdas#7]
@ziobron Wrong path and because of that bonus tests fails....
[https://github.com/coders-school/lambdas/commit/d0bd9220cfdd5acdeecc6cf89a1316c8f5c84ff0#r55959144](url)

**Comment by ziobron** [comment]
🏅 2 XP granted for @piotrku91
Thanks for raising this Issue to help to make the course better!

**Comment by ziobron** [comment]
Fixed in c8f46dc. Thanks!
